### Get all blogs
GET http://localhost:3001/api/blogs
Accept: application/json

### Add a new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Testi",
  "author": "Joona",
  "url": "http://testi.com",
  "likes": 1,
  "userId": "68d3df8c6f1e54e7337ca013"
}

### Update blog
PUT http://localhost:3001/api/blogs/68cc2fe77eac83e97cb2d7c6
Content-Type: application/json

{
  "title": "Test2",
  "author": "Joona",
  "url": "http://testi.com",
  "likes": 100
}